### ISSUE TITLE
Domoticz Log in Dashticz [Feature Request]

### ISSUE THREAD

**Issue by htilburgs** [robgeerts/dashticz_v2#100]
Present the Domoticz Log in the 'Domoticz Layout' - With the current URL it's not easy to read

> buttons.domoticz = {width:12, icon:'fa-microchip', title: 'Domoticz Log', url: 'http://192.168.0.100:8088/json.htm?type=command&param=getlog&loglevel=2'}

**Comment by robgeerts** [comment]
Check:
http://www.domoticz.com/forum/viewtopic.php?f=67&t=16526&p=141252
