### ISSUE TITLE
Add DAR to trash calendar [Feature request] 

### ISSUE THREAD

**Issue by G3rwin** [robgeerts/dashticz_v2#133]
Can you add DAR to the trash calendar
The website is: https://afvalkalender.dar.nl

I've added it myself, but I need to do this again with every update.
It used the same way as gemeenteberkelland.

Thanks in advance

G3rwin

**Comment by robgeerts** [comment]
Added to latest Beta, could you test this?
You can select Dar in the settings-popup.

**Comment by G3rwin** [comment]
Thnx Rob, its works :) BETA looks nice by the way.

**Comment by robgeerts** [comment]
Thanks!
