### ISSUE TITLE
config is not defined

### ISSUE THREAD

**Issue by HomeServ** [robgeerts/dashticz_v2#141]
main.js?v=1502200651799:55 Uncaught ReferenceError: config is not defined main.js?v=1502200651799

    at loadFiles (main.js?v=1502200651799:55)
    at (index):82
    at f (head.js:6)
    at head.js:6
    at head.js:6
    at HTMLScriptElement.o (head.js:6)

[CONFIG.js.txt](https://github.com/robgeerts/dashticz_v2/files/1208318/CONFIG.js.txt)

**Comment by mattijsf** [comment]
I got the same error using a fresh clone of master (38383b2)

**Comment by mattijsf** [comment]
After removing [line 55](https://github.com/robgeerts/dashticz_v2/blob/38383b2c01b14505cddcdff8e92db37027d97c26/js/main.js#L55):
```js
else if(typeof(config.language)!=='undefined'){ setLang = config.language}
```
I got it to work. For now.

**Comment by robgeerts** [comment]
Could you try latest version (doesnt matter if it is beta or master ;)

**Comment by HomeServ** [comment]
I've removed en recloned the "master".
Now I get the default, non configured, page while I've got the config file present as attached before.

**Comment by robgeerts** [comment]
Could we have a teamviewer session?
Could you send me your ID and password (If installed, otherwise, please install :)

**Comment by mattijsf** [comment]
I got it to work now. I didn't have a previous configuration so I don't have any further issues.

**Comment by HomeServ** [comment]
@robgeerts, how can I contact you?

**Comment by robgeerts** [comment]
robgeerts@gmail.com

**Comment by sschouten** [comment]
Hey rob,

after a fresh install now it is working :)

**Comment by robgeerts** [comment]
Great!

**Comment by HomeServ** [comment]
Looks like it is working over here as well. Thanks for the quick update!

**Comment by sschouten** [comment]
When i fill in the settings en need to place that in the config file, but where in the config file i need to do that ?

**Comment by robgeerts** [comment]
At the top.
Take a look at my exmaple config.js in the attachment of the first post in this topic:
http://www.domoticz.com/forum/viewtopic.php?f=67&t=17426
