### ISSUE TITLE
publictransport: support for more 9292 departure-time id's

### ISSUE THREAD

**Issue by Eddy805** [robgeerts/dashticz_v2#142]
For the `publictransport.js` module, the 9292 api offers more than the currently implemented id's `train` and `bus`. For location id `station-amsterdam-lelylaan`, for example, busses are combined with trams, using the id `tram-bus`. 

Also on this station, departures for the subway are available with id `metro`.

Example: [https://api.9292.nl/0.1/locations/station-amsterdam-lelylaan/departure-times?lang=nl-NL](https://api.9292.nl/0.1/locations/station-amsterdam-lelylaan/departure-times?lang=nl-NL)

**Comment by robgeerts** [comment]
Does it work as expected for you now?
