### ISSUE TITLE
CONFIG_DEFAULT.js not valid for latest update

### ISSUE THREAD

**Issue by mattijsf** [robgeerts/dashticz_v2#145]
I'm new to dashticz but it seems like the default configuration is not valid for the latest release.

The line:
```js
columns[1]['blocks'] = ['currentweather_big','weather',trashcan.afvalapp]
```

Is not valid and based on the `js/blocks.js` file I figured I had to change the last item to 'garbage' like so:
```js
columns[1]['blocks'] = ['currentweather_big','weather','garbage']
```

**Comment by robgeerts** [comment]
Thanks, fixed it!!
