### ISSUE TITLE
Support for EvoHome devices and Smoke detectors

### ISSUE THREAD

**Issue by wimmme** [robgeerts/dashticz_v2#161]
Hello,
I was using a version of dashticz before (20170622) where I had to make some changes in the code to get my Honeywell Evohome temperatures (type=Heating) and my KD101 smoke detectors (type=Security) showing in dashticz.
This was pretty straightforward, just adding some types in main.js.
But with the newer version DashticzV2 I cannot get this to work again. Is it possible to support these devices ? Or am i doing something wrong ?

**Comment by robgeerts** [comment]
Hi wimmme, wich changes did you make?

**Comment by wimmme** [comment]
I must add that my Evohome are still oldstyle; not the new Web API yet. 

in main.js, function getDevices(override) I added heating as type twice:
This used to work in DashticzV2 from 22/06/2017

`if($('.block_'+idx).length<=0){
								if(
									device['Type']=='Thermostat' || 
									device['Type']=='Temp + Humidity' || 
									device['Type']=='Temp + Humidity + Baro' || 
									device['Type']=='Usage' || 
									device['Type']=='Temp' || 
									device['Type']=='Humidity' || 
									device['Type']=='General' || 
									device['Type']=='Wind' || 
									device['Type']=='Rain' || 
									device['Type']=='RFXMeter' || 
									device['Type']=='P1 Smart Meter' || 
									device['Type']=='P1 Smart Meter USB' || 
									device['Type']=='Group' || 
									device['Type']=='Scene' ||  
									device['Type']=='Heating' ||  
									device['SwitchType']=='Motion Sensor' || 
									device['SwitchType']=='Smoke Detector' || 
									device['SwitchType']=='Contact'`

and

`else if(
									device['Type']=='Temp + Humidity + Baro' || 
									device['Type']=='Temp + Humidity' || 
									device['Type']=='Humidity' ||
									device['Type']=='Heating'
								){`

Keep up the good work, this is a wonderful project. I am using DashticzV2 on a 24" android tablet in my kitchen, A lot of people admired your interface there ;-)

**Comment by robgeerts** [comment]
I added these types to latest beta, but what is not working exactly?
Could you send me the JSON-output so I can test with this? You can get it here:

http://**DOMOTICZ_ADDRESS_AND_PORT**/json.htm?type=devices

**Comment by wimmme** [comment]
Not seeing my devices...

Hope the output is usefull, let me know if i can do sth...


Op 26 september 2017 21:08:24 schreef Rob Geerts <notifications@github.com>:

**Comment by robgeerts** [comment]
Where's your output?

**Comment by wimmme** [comment]
[json.txt](https://github.com/robgeerts/dashticz_v2/files/1336855/json.txt)

Sorry, replied by mail but github didn't take the html attachment ...

**Comment by robgeerts** [comment]
In latest beta, these types are working fine... Did you try latest beta?

**Comment by wimmme** [comment]
I hate to say this but you can stop the quest, its working now.

 

Did a complete rebase, download, config for the third time.

Only difference is I use the new Evohome API based devices now instead of the older script based.

 

Diffing the configs to find other changes, but except for the obvious

var _LANGUAGE = 'nl_NL';           ->            config['language'] = 'nl_NL';

 

I can’t see anything different. 

Anyway, thanks for your interface and your help, keep up the good work
