### ISSUE TITLE
Editor not saving?

### ISSUE THREAD

**Issue by ggamehdtv** [robgeerts/dashticz_v2#176]
Hello,

I just tried installing dashticz_v2 on domoticz stable running. I am seeing the switches but when I try to use the editor mode to add radio and stuff it doesn't save it? I can add it to the dashboard but save is not working. It just keeps getting back to switches only when clicking refresh of the page.

My config:
/*
var config = {}
config['domoticz_ip'] = 'http://192.168.2.150:8080';
config['app_title'] = 'Dashticz';
config['domoticz_refresh'] = '5';
config['dashticz_refresh'] = '60';

var trashnames = {}
trashnames['Gft'] = 'GFT';
trashnames['Pmd'] = 'Plastic';
trashnames['Rest'] = ''; //LEAVE EMPTY IF YOU WANT TO HIDE IT

var publictransport = {}
publictransport.ovinfobus = { show_via: false, station: 'son-en-breugel/bushalte-penseelkever', provider: '9292-bus', icon: 'bus', width:5, results: 6 }

var tvguide = {}
tvguide.dutch = { key:'dutch', icon: 'fa-television', width:7, channels: [1,3,4,31,46,92], maxitems: 5 }

var _STREAMPLAYER_TRACKS  	= [
	{"track":1,"name":"Q-music","file":"http://icecast-qmusic.cdp.triple-it.nl/Qmusic_nl_live_96.mp3"},
	{"track":2,"name":"538 Hitzone","file":"http://vip-icecast.538.lw.triple-it.nl/WEB11_MP3"},
	{"track":3,"name":"Slam! NonStop","file":"http://stream.radiocorp.nl/web10_mp3"},
	{"track":4,"name":"100%NL","file":"http://stream.100p.nl/100pctnl.mp3"},
  ]; 

var buttons = {}
buttons.nunl = {key: 'nunl',  width:12, icon: 'fa-newspaper-o', title: 'Nu.nl', newwindow:true, url: 'http://www.nu.nl'}
buttons.nos = {key: 'nos',  width:12, icon: 'fa-newspaper-o', title: 'Nos', url: 'http://www.nos.nl'}

var blocks = {}
blocks['blocktitle_1'] = {}
blocks['blocktitle_1']['key'] = 'blocktitle_1';
blocks['blocktitle_1']['type'] = 'blocktitle';
blocks['blocktitle_1']['title'] = 'Example';

var columns = {}
columns['bar'] = {}
columns['bar']['blocks'] = ['logo','miniclock','settings']
					
columns[1] = {}
columns[1]['blocks'] = ['currentweather_big','weather','garbage']
columns[1]['width'] = 5;

columns[2] = {}
columns[2]['blocks'] = ['blocktitle_1',tvguide.dutch,publictransport.ovinfobus]
columns[2]['width'] = 5; 

columns[3] = {}
columns[3]['blocks'] = ['sunrise','streamplayer',buttons.nunl,buttons.nos]
columns[3]['width'] = 2; 

var columns_standby = {}
columns_standby[1] = {}
columns_standby[1]['blocks'] = ['clock','weather']
columns_standby[1]['width'] = 12;

var screens = {}
screens[1] = {}
screens[1]['background'] = 'bg2.jpg';
screens[1]['columns'] = [1,2,3]
*/

Thanks in advance.
Justinn

**Comment by robgeerts** [comment]
First, you have to remove /* (in the begin) and */ (at the end).
When you save the editor mode, you can see some output, you have to save it to config.js

**Comment by ggamehdtv** [comment]
I removed the /* from the end and beginning of the config but I am not getting into editor mode anymore after refresh? Also when I click save when making changes it doesn't give me a code to copy and paste in the config. the setting screen just goes away.

**Comment by ggamehdtv** [comment]
Added radio:
![image](https://user-images.githubusercontent.com/19870029/32390995-c4e9c66a-c0d0-11e7-9398-74747e8aa7ac.png)

then I clicked save on right bottom and on settings right top but both are not saving or giving my a code to copy.

**Comment by ggamehdtv** [comment]
Also when I copy a working dasboard from the internet it is not changing when make changes in config and custom css.

**Comment by ggamehdtv** [comment]
Looks like I found what I did wrong.
But I am having another question now. Dashticz is connected to domoticz but the lamps/switches are not showing? do I need to add something to the config first before it is visible?

**Comment by gitmoplex** [comment]
NICE

after install i get the same thing.
A nice dashboard with all the switches working from domotics.
Then try and edit ( using windows edge) does not do a thing.

then try to remove the */ and /* from CONFIG.js.
Now the dashboard has some other options , radio and bus lines.
But where is domotics ? and i still cant edit.

I installed the lated github copy

thANK YIU

**Comment by robgeerts** [comment]
Whats your latest config.js? 
The edit mode from the screenshots above is not meant to be used (yet)

**Comment by gitmoplex** [comment]
ah i was under the assumption it worked like that ..
