### ISSUE TITLE
No devices in dashboard?

### ISSUE THREAD

**Issue by ggamehdtv** [robgeerts/dashticz_v2#180]
Hello,

I just installed dashticz again it's working amost now the only thing which is not working is the devices from domoticz. These are not visible on the dashboard but I added the right ip and port to the config. Do I need to add another thing before it should work?

Config:

var config = {}
config['domoticz_ip'] = 'http://192.168.2.150:8080';
config['app_title'] = 'Dashticz';
config['domoticz_refresh'] = '1';
config['dashticz_refresh'] = '1';
config['auto_positioning'] = 0;
config['standby_after'] = 0;
config['default_news_url'] = 'http://www.nu.nl/rss/algemeen';
config['slide_effect'] = 'slide';
config['timeformat'] = 'DD-MM-YY HH:mm';
config['boss_stationclock'] = 'RedBoss';
config['wu_api'] = '68120097c48b1a85';
config['wu_city'] = 'Roermond';
config['wu_name'] = '';
config['wu_country'] = 'NL'
config['last_update'] = 1;
config['hide_topbar'] = 0;
config['hide_seconds'] = 0;
config['hide_seconds_stationclock'] = 0;
config['use_fahrenheit'] = 0;
config['use_beaufort'] = 0;
config['translate_windspeed'] = 1;
config['static_weathericons'] = 0;
config['hide_mediaplayer'] = 0;
config['selector_instead_of_buttons'] = 1;
config['garbage_company'] = 'cure';
config['garbage_icalurl'] = 0;
config['garbage_zipcode'] = '6042WE';
config['garbage_street'] = 'Veldbrand';
config['garbage_housenumber'] = '2';
config['garbage_maxitems'] = '12';
config['garbage_width'] = '12';
config['garbage_hideicon'] = 0;

var trashnames = {}
trashnames['Gft'] = 'GFT';
trashnames['Pmd'] = 'Plastic';
trashnames['Rest'] = ''; //LEAVE EMPTY IF YOU WANT TO HIDE IT

var publictransport = {}
publictransport.ovinfobus = { show_via: false, station: 'son-en-breugel/bushalte-penseelkever', provider: '9292-bus', icon: 'bus', width:5, results: 6 }

var tvguide = {}
tvguide.dutch = { key:'dutch', icon: 'fa-television', width:7, channels: [1,3,4,31,46,92], maxitems: 10 }

var _STREAMPLAYER_TRACKS  	= [
	{"track":1,"name":"Q-music","file":"http://icecast-qmusic.cdp.triple-it.nl/Qmusic_nl_live_96.mp3"},
	{"track":2,"name":"538 Hitzone","file":"http://vip-icecast.538.lw.triple-it.nl/WEB11_MP3"},
	{"track":3,"name":"Slam! NonStop","file":"http://stream.radiocorp.nl/web10_mp3"},
	{"track":4,"name":"100%NL","file":"http://stream.100p.nl/100pctnl.mp3"},
        {"track":5,"name":"Vastelaovend","file":"http://www.radiovastelaovend.nl/templates/rav/luister.m3u"},
  ]; 

var buttons = {}
buttons.nunl = {key: 'nunl',  width:12, icon: 'fa-newspaper-o', title: 'Nu.nl', newwindow:true, url: 'http://www.nu.nl'}
buttons.nos = {key: 'nos',  width:12, icon: 'fa-newspaper-o', title: 'Nos', url: 'http://www.nos.nl'}
buttons.radio = {width:12, image: 'img/radio_on.png', title: 'Radio', url: 'http://nederland.fm'}
buttons.buienradar = {width:22, isimage:true, refreshimage:60000, image: 'http://api.buienradar.nl/image/1.0/RadarMapNL?w=285&h=256', url: 'http://www.weer.nl/verwachting/nederland/son/189656/'}
buttons.afval = {width:12, icon: 'fa-trash-o', title: 'Afval', url: 'https://www.recyclemanager.nl/afvalkalender/1321LJ/10'}
buttons.moon= {width:12, isimage:true, refreshimage:60000, image: 'moon'}

var blocks = {}
blocks['blocktitle_1'] = {}
blocks['blocktitle_1']['key'] = 'blocktitle_1';
blocks['blocktitle_1']['type'] = 'blocktitle';
blocks['blocktitle_1']['title'] = 'Schakelaars';

blocks['blocktitle_2'] = {}
blocks['blocktitle_2']['key'] = 'blocktitle_2';
blocks['blocktitle_2']['type'] = 'blocktitle';
blocks['blocktitle_2']['title'] = 'Weer';

blocks['104'] = {}
blocks['104']['key'] = '104';
blocks['104']['title'] = 'TV';
blocks['104']['switch'] = true;

var columns = {}
columns['bar'] = {}
columns['bar']['blocks'] = ['logo','miniclock','settings']
					
columns[1] = {}
columns[1]['blocks'] = ['blocktitle_1','garbage']
columns[1]['width'] = 5;

columns[2] = {}
columns[2]['blocks'] = ['blocktitle_2','weather',tvguide.dutch,publictransport.ovinfobus]
columns[2]['width'] = 5; 

columns[3] = {}
columns[3]['blocks'] = ['sunrise','streamplayer',buttons.nunl,buttons.nos,buttons.radio,buttons.buienradar]
columns[3]['width'] = 2; 

var columns_standby = {}
columns_standby[1] = {}
columns_standby[1]['blocks'] = ['clock','weather']
columns_standby[1]['width'] = 12;

var screens = {}
screens[1] = {}
screens[1]['background'] = 'bg2.jpg';
screens[1]['columns'] = [1,2,3]

**Comment by robgeerts** [comment]
What if you add this variable to CONFIG.js?

config['use_favorites'] = 0;
