### ISSUE TITLE
Switch title and value for multi-value devices

### ISSUE THREAD

**Issue by mjf2708** [robgeerts/dashticz_v2#184]
Presently, it is not possible to switch title and value for multi-value devices, e.g., Temp + Humidity.
This can be achieved in main.js by changing lines such as:

`html+=getStateBlock(device['idx']+'a',icon,title,number_format(device['Temp'],1,',','.')+_TEMP_SYMBOL,device);`

to:

`if(typeof(blocks[idx+'_1'])!=='undefined' && typeof(blocks[idx+'_1']['switch'])!=='undefined' && blocks[idx+'_1']['switch']==true){
	 html+=getStateBlock(device['idx']+'_1',icon,number_format(device['Temp'],1,',','.')+_TEMP_SYMBOL,title,device);}
else {
	html+=getStateBlock(device['idx']+'_1',icon,title,number_format(device['Temp'],1,',','.')+_TEMP_SYMBOL,device);
}`

(applies elsewhere, e.g., energy devices)

**Comment by robgeerts** [comment]
Please test this in latest version!

**Comment by mjf2708** [comment]
This isn't working correctly. The 'if' and 'else' clauses are the wrong way round - MY MISTAKE! SORRY!
Should be: 'if ... title, number ... else ... number, title'
Also, for humidity it's necessary to change
`html= getStateBlock(device['idx']+'b'...`
to
`html= getStateBlock(device['idx']+'_2'`
and similarly for barometer (['idx'+'c' to ['idx'+'_3').
The line after
`var icon = 'fa fa-thermometer-half';`
refers to idx+'_3' - shouldn't this be idx+'_1'?

I've made similar changes for my Owl energy meter - device type 'General', sub-type 'kWh' (and I suspect needed for other energy / meter devices, though I don't have these).

**Comment by robgeerts** [comment]
Thanks, fixed in latest beta!
