### ISSUE TITLE
html in text device

### ISSUE THREAD

**Issue by papo-o** [robgeerts/dashticz_v2#190]
is there a possibility to interpret the html tags contained in the text devices in order to respect the formatting of the text? (only font and color)
or possibly delete the tags completely and only display the text contained in the device
![2017-11-14 18_04_37-dashboard _ reacticz](https://user-images.githubusercontent.com/25136535/32795594-7b4c4ccc-c96c-11e7-8496-f70f9b3b3251.png)

**Comment by robgeerts** [comment]
Check this image: https://imgur.com/PL8mNfa
Seems to work here...

I tested this by adding the value in LUA like this:

`ttidx = 381
newtext = 'New <font color="#999">text</font>'
commandArray['UpdateDevice'] = ttidx..'|0|'..newtext`

**Comment by papo-o** [comment]
work fine now 
thank you
