### ISSUE TITLE
Google Analytics disabling per config (Feature request)

### ISSUE THREAD

**Issue by aalwash** [robgeerts/dashticz_v2#230]
Hi,

I was starting to configure Dashticz, the idea of the add-on, next to Domoticz is clever.
And I checked some pictures of the Domoticz forum and the end results look cool.

But I was wondering, I noticed a Google Analytics code in index.html and index2.html

I'm all oke with you tracking all statistics for yourself, to find out how many people use it and maybe how?

But, I'm worried, why isn't this a config option? (Default enabled? Whatever you like)
So the person that configures Dashticz can decide if he/she wants to share all stats + URL's?

If someone for some reason forgot to protect his URL's and they are public, you could see the URL's in Google Analytics.
Which means, you have access to their Domoticz and in some cases (full) control over their house.

I still have faith in humanity, that wasn't your goal nor you're doing such things ;)

Just consider my feature request.

Talking about this GA code:
`<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
		  ga('create', 'UA-102837285-1', 'auto');
		  ga('send', 'pageview');
		</script>`

**Comment by robgeerts** [comment]
Hey :)
Thanks for your suggestion and using Dashticz!
This feature request is already on our todo list.

It's indeed ONLY used to track how many users are using it (currently 1.337) and wich devices Dashticz is used on.

**Comment by aalwash** [comment]
Haha, funny number 1337 ;)

Good to here that you're using the statistics only to determine which technologies you can use.
I'm a programmer myself, so maybe I will build some new features fix bugs in the future :)

Good job! 👍 

Now that we're talking about statistics, do you know the top 10 browsers that are used?
The reason I'm asking, so I know if it's possible to start building plugins hooks and use more ECMA6 script.
The plugin hooks, well, for the plugins ;)
And the ECMA6, because it has classes and is much cleaner code then purely using JS functions

**Comment by robgeerts** [comment]
I had to laugh too ;) 
Although, its the amount of unique users last month only.

In latest beta it should be possible to disable Google Analytics via settings!
Top 25 browsers, in the last 3 months are: http://prntscr.com/htai1f
Please, use script that is compatible with these browsers, otherwise the forum gets overloaded with bug reports ;)

**Comment by aalwash** [comment]
Thanks for the overview! This gives me some good indication what the possibilities are.

And of course, as a programmer I know how important it is to keep the code working for the mainstream browsers.
