### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ayahuasca** [robgeerts/dashticz_v2#233]
Hello,

I have a new installation of Domoticz with some zwave hardware and devices. I have it installed on a Synology with ssl enabled https://192.168.1.2:8443 . After installing and settingup Domoticz I git cloned dashticz_v2 master to /volume1/@ appstore/domoticz/www/dashboard and chmod all files and folders to domoticz:root as all file in the www folder are. 

I copied the custom/CONFIG_DEFAULT.js to custom/CONFIG.js and changed the ìp address to https://192.168.1.2:8443

Now I tried to open https://192.168.1.2:8443/dashboard but all I get is: 500 Internal Server Error

And now I am stuck. Do you have any suggestions?

**Comment by aiolos** [comment]
I'm not sure how the Synology handles the requests, but you can try https://192.168.1.2:8443/dashboard/ (note the extra slash(/)) or https://192.168.1.2:8443/dashboard/index.html

**Comment by ayahuasca** [comment]
'dohh, that extra / in the url did it. This probably is a apache config thing?

**Comment by aiolos** [comment]
Cool, yes, it has something to do with apache config I think. Apache should check whether the requested url is a folder (or something like that). Unfortunately I don't know a lot about apache config, so I can't help you with that.
