### ISSUE TITLE
City name not displayed in title of weather block, if not defined in the config

### ISSUE THREAD

**Issue by aalwash** [robgeerts/dashticz_v2#241]
Hi,

When you don't define wu_name in the configuration, the wu_city isn't used.
The reason, because the below if statement is true, when the item isn't there.
`if(settings['wu_name'] !== '' && settings['wu_name'] !== 0) // in js/weather.js`

**Comment by aalwash** [comment]
In case people don't know which weather block I mean, see screenshot

![image](https://user-images.githubusercontent.com/3220347/34644243-ec989954-f332-11e7-8044-475e6755c15b.png)

**Comment by Dylantje** [comment]
Perhaps try this:
`config['wu_city'] 		= 'City of weather underground';
config['wu_name'] 		= 'Your city??';`

**Comment by aalwash** [comment]
Yes, that works.

But the bug is, if you fill in the wu_city but don't fill in the wu_name, it should use the wu_city instead (based on the code).

I already fixed the bug and send a PR

**Comment by aalwash** [comment]
PR accepted, closing ticket
