### ISSUE TITLE
Custom crossorigin.me server [idea]

### ISSUE THREAD

**Issue by adrianmihalko** [robgeerts/dashticz_v2#26]
Maybe everybody should run they own crossorigin.me server? I got it working, since it is an open source project. 

...maybe we should make 'https://crossorigin.me' into a configurable variable in CONFIG.js =>>>> _CROSS_PROXY_URL = '' so everybody can set they own cross proxy server (=or run it's own)? 

**Install node & npm:**
```
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo curl -L https://www.npmjs.com/install.sh | sh

```

**Clone crossorigin.me repo:**
```
https://github.com/technoboy10/crossorigin.me.git crossorigin
cd crossorigin
npm install
npm start
```

...but it's for advanced users only.

**Comment by robgeerts** [comment]
Not really an issue anymore.
