### ISSUE TITLE
When (outside) temperature drops below zero

### ISSUE THREAD

**Issue by mvveelen** [robgeerts/dashticz_v2#33]
Not an issue, but a request for an enhancement:

When a temperature reading drops below zero, could the value be in blue (or whatever color you like) ? Like a warning for frost when you have to leave home by car.

Selectable by the user (var _USE_TEMP_COLOR = "#F0F0F0"; or something like that). If not set, use default.

**Comment by robgeerts** [comment]
Take a look at:
http://www.domoticz.com/forum/viewtopic.php?f=67&t=17657
