### ISSUE TITLE
Custom background images in custom folder [enhancement]

### ISSUE THREAD

**Issue by rbisschops** [robgeerts/dashticz_v2#34]
Suggest to put custom background images in the custom folder (eventually maybe even in a subfolder images or img to stay in line with the dir structure). This way custom images won't be overwritten when the folder is updated/replaced with a new version of the dashboard. This requires the path to the custom images to be set in config.js as part of the configuration.
Current (line 156, main.js):
`if(typeof(screens[s]['background'])!=='undefined') screenhtml+='style="background-image:url(\'img/'+screens[s]['background']+'\');"';`
Suggestion (line 156, main.js):
`if(typeof(screens[s]['background'])!=='undefined') screenhtml+='style="background-image:url('+screens[s]['background']+');"';`

**Comment by robgeerts** [comment]
Now possible in latest beta!
Try:

`screens[1]['background'] = 'custom/bg9.jpg';`
