### ISSUE TITLE
Standby screen

### ISSUE THREAD

**Issue by HoekieN** [robgeerts/dashticz_v2#36]
columns_standby[1]['blocks'] = ['clock','currentweather_big','weather',5]

'currentweather_big','weather',5 ect, only work in the standby screen when the are also used in the columns section.
If there not used in the columns the will not show up in the standby screen.

Example:
This don't work:
columns[2]['blocks'] = ['blocktitle_2',14,23,9,12,19]
columns_standby[1]['blocks'] = ['clock','currentweather_big','weather',5]

This works:
columns[2]['blocks'] = ['blocktitle_2',14,23,9,12,19,**'currentweather_big','weather',5**]
columns_standby[1]['blocks'] = ['clock',**'currentweather_big','weather',5**]

**Comment by robgeerts** [comment]
This should be fixed in latest beta!
