### ISSUE TITLE
Garbage calendar Twente milieu

### ISSUE THREAD

**Issue by nvdael** [robgeerts/dashticz_v2#425]
The is a problem with the Garbage calendar and Twente Milieu.
All of the containers are of pickuptype 0, so this is always the gray one.

Dump of datalist returned:
    "dataList": [
        {
            "pickupDates": [],
            "pickupType": 0,
            "_pickupType": 0,
            "_pickupTypeText": "GREY",
            "description": "BO ZL14 BRWO"
        },
        {
            "pickupDates": [
                "2019-01-23T00:00:00"
            ],
            "pickupType": 0,
            "_pickupType": 0,
            "_pickupTypeText": "PACKAGES",
            "description": "BO ZL14 DVWO"
        },
        {
            "pickupDates": [
                "2019-01-16T00:00:00",
                "2019-01-30T00:00:00"
            ],
            "pickupType": 0,
            "_pickupType": 0,
            "_pickupTypeText": "GREEN",
            "description": "BO ZL14 OGWO"
        }
    ],

**Comment by robgeerts** [comment]
Sorry for the late response but this is fixed in latest BETA. (2.5.9)
