### ISSUE TITLE
Can't get the garbage working (version 2.5.1)

### ISSUE THREAD

**Issue by KentuckyMC** [robgeerts/dashticz_v2#430]
Hi all,

I've some troubles to get the garbage calendar working. In some versions before, when all the calls were going to the dashticz.nl domain, everything works fine. Now I've setup my own server and got the Google calendar already working again. The garbage collection isn't working yet. When I debug the url that fires (from the garbage.js) I get something like this (without real data): 

`http://182.188.1.100/dashticz/vendor/dashticz/garbage/?service=mijnafvalwijzer&sub=undefined&zipcode=1234AA&nr=1&t=`

In the result, I get the data of my garbage calendar, but that's it. The code won't go inside the result data of the getJSON. The result of the call is:

`http://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode=1234AA&street=&huisnummer=1&toevoeging=[{"date":"2019-01-24","title":"gft"},{"date":"2019-01-31","title":"restafval"},{"date":"2019-02-07","title":"gft"} etc.`

My config looks like:
`config['garbage_company'] = 'mijnafvalwijzer';
config['garbage_icalurl'] = '';
config['garbage_zipcode'] = '1234AA';
config['garbage_street'] = 'streetname';
config['garbage_housenumber'] = '1';
config['garbage_housenumberadd'] = '';
config['garbage_maxitems'] = '12';
config['garbage_width'] = '12';
config['garbage_hideicon'] = 0;
config['garbage_use_names'] = true;
config['garbage_use_colors'] = true;
config['garbage_icon_use_colors'] = true;
config['garbage_use_cors_prefix'] = true;
config['garbage'] = {
    gft: {kliko: 'green', code: 'lightgreen', name: 'GFT', icon: 'img/garbage/kliko_green.png'},
    pmd: {kliko: 'orange', code: 'orange', name: 'PMD', icon: 'img/garbage/kliko_orange.png'},
    rest: {kliko: 'white', code: 'white', name: 'Restafval', icon: 'img/garbage/kliko_grey.png'},
    kca: {kliko: 'red', code: '#b21807', name: 'Chemisch afval', icon: 'img/garbage/kliko_red.png'},
    brown: {kliko: 'brown', code: '#7c3607', name: 'Bruin', icon: 'img/garbage/kliko_brown.png'},
    black: {kliko: 'black', code: '#000000', name: 'Zwart', icon: 'img/garbage/kliko_black.png'},
    milieu: {kliko: 'yellow', code: '#f9e231', name: 'Geel', icon: 'img/garbage/kliko_yellow.png'},
    kerstboom: {kliko: 'green', code: '#375b23', name: 'Kerstboom', icon: 'img/garbage/tree.png'},
};`

**Comment by lokonli** [comment]
Can you send me a valid zipcode, streetname and housenumber, which can be used with mijnafvalwijzer.nl? I'll test it on my configuration.

**Comment by lokonli** [comment]
Is  rova collecting garbage in your area? Is rova working?

**Comment by KentuckyMC** [comment]
There is a demo with zipcode: 3825AL and housenumber 41. It is the "Lindeboomseweg". If you fill it in at mijnafvalwijzer.nl it works ;)

**Comment by KentuckyMC** [comment]
> Is rova collecting garbage in your area? Is rova working?

Rova isn't working at our place. The mijnafvalwijzer was always working, but since the removal of dashticz.nl it's not. My normal google calendar is working with my own webserver and the call seems to be fine for the afvalwijzer as well, but nothing happens.

**Comment by lokonli** [comment]
The URL which is being called (with the demo address) is:
http://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode=3825AL&street=&huisnummer=41&toevoeging=

This doesn't return any valid garbage pickup data anymore.

The given address is in Amersfoort. According to https://www.amersfoort.nl/afval.htm the garbage is collected by Rova.
Rova doesn't work for the demo address, but that might be because it's not a domestic but an industrial area. For a random house from Funda (3826 CD, nr. 17) Rova is working. However, www.mijnafvalwijzer.nl doesn't recognize this address.

If you can give me an example for json.mijnafvalwijzer.nl (zipcode+housenumber) that returns valid data I can further analyze it.

**Comment by lokonli** [comment]
I've found one:
http://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode=3842CR&street=&huisnummer=1&toevoeging=

I'll check ...

**Comment by lokonli** [comment]
With this address (3842CR, 1) Dashticz and mijnafvalwijzer are working for me...

Can you check this address with your system?

**Comment by KentuckyMC** [comment]
> With this address (3842CR, 1) Dashticz and mijnafvalwijzer are working for me...
> 
> Can you check this address with your system?

I will check this address tomorrow. I'm not able to do this this evening. Thanks for diving into this.

**Comment by KentuckyMC** [comment]
Sorry for the late reply. I got the same issue when using my own address, the widget stays on "loading". I got the same output:

`http://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode=3842CR&street=&huisnummer=1&toevoeging=[{"date":"2019-01-02","title":"grofvuil"},{"date":"2019-01-02","title":"kca"},{"date":"2019-01-04","title":"gft"},{"date":"2019-01-10","title":"kerstbomen"},{"date":"2019-01-11","title":"restafval"},{"date":"2019-01-16","title":"grofvuil"},{"date":"2019-01-18","title":"gft"},{"date":"2019-01-25","title":"restafval"},{"date":"2019-01-28","title":"papier"},{"date":"2019-01-30","title":"grofvuil"},{"date":"2019-02-01","title":"gft"},{"date":"2019-02-04","title":"textiel"},{"date":"2019-02-06","title":"kca"},{"date":"2019-02-08","title":"restafval"},{"date":"2019-02-13","title":"grofvuil"},{"date":"2019-02-15","title":"gft"},{"date":"2019-02-22","title":"restafval"},{"date":"2019-02-25","title":"papier"},{"date":"2019-02-27","title":"grofvuil"}`

**Comment by lokonli** [comment]
With my system it works as it should, including your config and the zipcode/housenumber as provided above.

Do you see any other error in the Chrome developers console? or unexpected warnings?

**Comment by KentuckyMC** [comment]
No nothing.. seems that everything works fine. I'm also getting some output, maybe the url before that output is the issue? That the widget expects that that URL isn't there? I will try some more debugging tonight.

**Comment by robgeerts** [comment]
I checked this too, tested with zipcode 3825AL  and works as expected.
