### ISSUE TITLE
Counter not showing "count" instead shows "on"

### ISSUE THREAD

**Issue by Tontze** [robgeerts/dashticz_v2#44]
![lightning1](https://cloud.githubusercontent.com/assets/28216916/25618060/fd2bd3c0-2f4d-11e7-873c-b78faa7908d6.PNG)

**Comment by robgeerts** [comment]
Could you send me the JSON output of this device?

**Comment by Tontze** [comment]
`{
   "ActTime" : 1493733297,
   "ServerTime" : "2017-05-02 16:54:57",
   "Sunrise" : "05:11",
   "Sunset" : "21:32",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Counter" : "0 Strikes",
         "CounterToday" : "0",
         "CustomImage" : 0,
         "Data" : "0 Strikes",
         "Description" : "Counts lightning strikes nearby",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "General Dummy Devices",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : true,
         "ID" : "82149",
         "LastUpdate" : "2017-04-10 07:58:41",
         "Name" : "Lightning 15km radius",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Counter Incremental",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "counter",
         "Unit" : 1,
         "Used" : 1,
         "ValueQuantity" : "Count",
         "ValueUnits" : "Strikes",
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "149"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}`

**Comment by Tontze** [comment]
{
   "ActTime" : 1493733297,
   "ServerTime" : "2017-05-02 16:54:57",
   "Sunrise" : "05:11",
   "Sunset" : "21:32",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Counter" : "0 Strikes",
         "CounterToday" : "0",
         "CustomImage" : 0,
         "Data" : "0 Strikes",
         "Description" : "Counts lightning strikes nearby",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "General Dummy Devices",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : true,
         "ID" : "82149",
         "LastUpdate" : "2017-04-10 07:58:41",
         "Name" : "Lightning 15km radius",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Counter Incremental",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "counter",
         "Unit" : 1,
         "Used" : 1,
         "ValueQuantity" : "Count",
         "ValueUnits" : "Strikes",
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "149"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by robgeerts** [comment]
Thanks, fixed in next beta (not available yet!)
