### ISSUE TITLE
periods and commas in numbers reversed (2.5.5)

### ISSUE THREAD

**Issue by gohamstergo** [robgeerts/dashticz_v2#445]
On the dashticz page, I'm seeing numbers as "2.345,67" with the period and comma are reversed. Not sure of your country of origin, so maybe thats normal there :) , just hoping for a toggle or something to change numbers to "2,345.67"

Thanks!

**Comment by lokonli** [comment]
There is.

Add the following two lines to custom.js:

```
var _THOUSAND_SEPARATOR = ',';
var _DECIMAL_POINT = '.';

```

**Comment by gohamstergo** [comment]
thank you!
