### ISSUE TITLE
Feature request: Writing docs in the codebase

### ISSUE THREAD

**Issue by aalwash** [robgeerts/dashticz_v2#459]
Hi,

Wouldn't it be an idea to write the documentation in the codebase?
So let's say, we make a docs/ directory, there we can write the Markdown/RST files with all the features/configuration options?

The reason is simple, when someone writes a feature request, he/she can add a new file or modify a previous MD/RST file with the new config options

I noticed that the WIKI is already out-dated and missing a lot of config options

The nice part of adding docs in the Git, we can use a tool like: readthedocs.io
See for example: https://bootstrap-datepicker.readthedocs.io/en/latest/

Notice the /latest/, there you can choose any tag/branch
And the docs will change to that branch/tag 

What do you think? @robgeerts

**Comment by lokonli** [comment]
Indeed, we should improve the documentation. Last days I experimented a bit with the github wiki, but I think I prefer your proposal.
Can you create a first setup?

**Comment by robgeerts** [comment]
@aalwash @lokonli 
I had github wiki so prefer your setup too :)

**Comment by aalwash** [comment]
Here is a small start/example: https://aalwash-dashticzv2.readthedocs.io/en/docs-example/index.html

**Comment by lokonli** [comment]
Thanks for the example. I've extended it (structure only at the moment) and created a PR for it from my repository. See #467.

The documentation now is generated from my repository, see https://dashticz-v2.readthedocs.io, but it should connect to github.com/Dashticz/dashticz_v2.

@robgeerts can you help with the following:
Create an account on readthedocs,org, preferably via your github name (robgeerts).
Then add the webhook to readthedocs via:
https://github.com/Dashticz/dashticz_v2/settings/hooks

I'll send you the payload url by PM

**Comment by aalwash** [comment]
Nice first version, let's push this so we can start filling up the docs and all missing features 

And of course changing the Contribution guidelines to explain what to do if someone builds a new feature and where to modify the docs

**Comment by aalwash** [comment]
@lokonli so if I understand correctly, this has been moved to https://github.com/dashticzv3/dashticz_v3 ?

Because I'm not seeing @robgeerts  doing any PR anymore?

It's fine with me, but shouldn't it be communicated that V3 is the next release (beta atm), but all issues/PR's should be done there?

Also, if DashticzV3 is the main focus, maybe start implementing stuff beter.
Let's start with using tags in the repository ;), I already love the Changelog you added (https://dashticz-v3.readthedocs.io/en/beta/releasenotes.html)

Just an extra tag to 'freeze' the code, in case someone wants to fully revert to a specific version

**Comment by aalwash** [comment]
@lokonli  I think we can close this issue? The request has been fulfilled and the docs are part of the code now

PS: The new repository is now https://github.com/Dashticz/dashticz
There you can find the newest and most maintained version of Dashticz
