### ISSUE TITLE
RGB color selector

### ISSUE THREAD

**Issue by Tontze** [robgeerts/dashticz_v2#48]
Would like to have possibility to change RGB bulb/strip color same way as dimmer works now, possible double slider, upper dimmer, lower for color.

**Comment by Teunissm** [comment]
Is already someone started with this issue? I would be great to have an RGB dimmer in Dashticz

**Comment by robgeerts** [comment]
Take a look at: http://www.domoticz.com/forum/viewtopic.php?f=67&t=18309
Please discuss this in the forum.
