### ISSUE TITLE
enhancement : Popup webcam/camera screen when a switch (doorbell) is switched On

### ISSUE THREAD

**Issue by bsmeding** [robgeerts/dashticz_v2#55]
Can it be possible to popup the camera window when another switch is On like a doorbell so i can see in a large image who is in front of the door

**Comment by robgeerts** [comment]
Possible with executing an action... take a look at:
http://www.domoticz.com/forum/viewtopic.php?f=67&t=17537

**Comment by bsmeding** [comment]
Hi Rob, thanks that works perfect!
