### ISSUE TITLE
Use only local resources.

### ISSUE THREAD

**Issue by ultrara1n** [robgeerts/dashticz_v2#57]
While debugging the code i saw, beside all the local connection, that there is one resource which is not loaded locally but directly from Google. 

I'm talking about main.js, Line 38:
`$('<link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">').appendTo("head");`

I would prefer a local solution, as Google Fonts is Open Source and you could save the stylesheet directly to the css folder.

**Comment by robgeerts** [comment]
Will do :)

**Comment by robgeerts** [comment]
Check out latest beta!
