### ISSUE TITLE
Using undefined _EDIT_MODE in main.js

### ISSUE THREAD

**Issue by ultrara1n** [robgeerts/dashticz_v2#58]
Since the newest update of main.js, it is not possible to use Dashticz because of an error in line 126. _EDIT_MODE is checked there, but not if undefinied, only if its true.
Console reports that there is no _EDIT_MODE, so the check results in an error and therefore the Dashboard does not load anymore.

**Comment by robgeerts** [comment]
Will be fixed in next beta, wich is available in around half an hour ;)
In the meantime, add

var _EDIT_MODE = false; 

in config.js
