### ISSUE TITLE
Dimmer slider not changing stated %

### ISSUE THREAD

**Issue by Tontze** [robgeerts/dashticz_v2#59]
As you see, slider is under 50%, but it says 99%. 99% is not changed in any situation ?

![slider](https://cloud.githubusercontent.com/assets/28216916/25714091/92e00dde-30ff-11e7-9389-ec01f00771bb.PNG)

> {
   "ActTime" : 1494065994,
   "ServerTime" : "2017-05-06 13:19:54",
   "Sunrise" : "04:59",
   "Sunset" : "21:42",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 7,
         "HardwareName" : "Mi Light",
         "HardwareType" : "Limitless/AppLamp/Mi Light with LAN/WiFi interface",
         "HardwareTypeVal" : 22,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "1",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-05-06 13:16:19",
         "Level" : 45,
         "LevelInt" : 45,
         "MaxDimLevel" : 100,
         "Name" : "MiLight Bridge",
         "Notifications" : "false",
         "PlanID" : "11",
         "PlanIDs" : [ 11 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBWW",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "true",
         "Type" : "Lighting Limitless/Applamp",
         "TypeImg" : "dimmer",
         "Unit" : 5,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "676",
         "YOffset" : "15",
         "idx" : "123"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by robgeerts** [comment]
Please test this in latest beta!
