### ISSUE TITLE
Requests regarding the garbage add-on

### ISSUE THREAD

**Issue by mvveelen** [robgeerts/dashticz_v2#68]
Requests:

- Can we set the amount of days, so we can choose to only see 2, 3 or x days/collect-moments in advance? Configurable in CONFIG.js
- Can we change the names ourselves in CONFIG.js? (f.i. Gft -> GFT, Pmd -> Plastic, etc.) Configurable in CONFIG.js
- Can the color of the garbage bin be depending of the sort of garbage (orange when it's plastic, green when it's GFT, grey when it's Rest) ? Configurable in CONFIG.js
- Can the dates be aligned neatly ? Configurable in CONFIG.js

**Comment by robgeerts** [comment]
In latest beta you can change the names, add to config.js:

var trashnames = {}
trashnames['Gft'] = 'GFT';
trashnames['Pmd'] = 'Plastic';

(Gft becomes GFT and Pmd becomes Plastic)

Also you can change the colors:

var trashcolors = {}
trashcolors['Gft'] = 'Green';
trashcolors['Pmd'] = 'Orange';

**Comment by mvveelen** [comment]
Ik ga meteen weer updaten :)


Uitnodiging om de rammelende agenda te bekijken staat nog steeds hoor. Als je daar zin en tijd voor hebt natuurlijk. Ik begrijp namelijk dat ik niet de enige ben met dit issue.

Bedankt weer !

Gr,

Marco

**Comment by robgeerts** [comment]
Max items is also working now, change config.js and add maxitems like:

var trashcan = {}
trashcan.afvalapp = { key:'afvalapp', maxitems: 10, trashapp: 'deafvalapp', width:12,zipcode:'5692VG', housenumber:'33', country:'NL' }
