### ISSUE TITLE
history graph is not replacing old one, but adding on top old one

### ISSUE THREAD

**Issue by Tontze** [robgeerts/dashticz_v2#74]
See pictures below :) When you change from today to last week or other, it adds new graph on top of previous.

![lightning1](https://cloud.githubusercontent.com/assets/28216916/25899844/1e8631d0-359a-11e7-975f-0883aa8c5a82.PNG)
![lightning2](https://cloud.githubusercontent.com/assets/28216916/25899842/1e81de82-359a-11e7-8d27-e51037b46d5c.PNG)
![lightning3](https://cloud.githubusercontent.com/assets/28216916/25899843/1e8256f0-359a-11e7-80c5-319680a9cc3c.PNG)

**Comment by ultrara1n** [comment]
Can be closed :)
