### ISSUE TITLE
FlipClock [Feature Requests]

### ISSUE THREAD

**Issue by HansieNL** [robgeerts/dashticz_v2#77]
Would be nice to have a FlipClock on the dashboard:
[http://flipclockjs.com/](http://flipclockjs.com/)

**Comment by michal-adamek** [comment]
Done and waiting for merge.

**Comment by robgeerts** [comment]
Available now in beta!

**Comment by EdKo66** [comment]
Cool

**Comment by EdKo66** [comment]
How do you enable this? Tried 'FlipClock', 'flipclock' but didn't work

**Comment by aalwash** [comment]
@EdKo66 Just tested it with 'flipclock' (master branch) and it works

Maybe time to close this issue :)?
