### ISSUE TITLE
Maxlines for rss feed article [Feature Request]

### ISSUE THREAD

**Issue by HansieNL** [robgeerts/dashticz_v2#81]
Sometimes a rss just one article has 20 lines. Then are 20 lines reserved for this block. It would be great if a max value would be possible, then the block stays always same size.

**Comment by robgeerts** [comment]
In latest beta, try:

`blocks['news_1'] = {}
blocks['news_1']['feed'] = 'https://cors-anywhere.herokuapp.com/http://www.nu.nl/rss/Algemeen';
blocks['news_1']['maxheight'] = 113;`
