### ISSUE TITLE
Update to jQuery 2.2.4

### ISSUE THREAD

**Issue by ultrara1n** [robgeerts/dashticz_v2#97]
After testing Dashticz with jQuery 2.2.4 and there are no problems, since the API of jQuery had no change, i suggest updating to this version, since it is much more faster and smaller.
This would be better for battery driven devices and weak devices, since the Javascript compiler have less work to keep up Dashticz.
It only cuts compatibility with IE8, but to be honest, anyone who is using this today got other problems than broken jquery.

**Comment by robgeerts** [comment]
Updated in beta!
