### ISSUE TITLE
Calendar - Image or Icon [Feature Request]

### ISSUE THREAD

**Issue by htilburgs** [robgeerts/dashticz_v2#99]
Is it possible to choose between icon or image, so we can use our own image (like F1 in Formule1 Calendar) like in example??

> calendars.f1 = { maxitems: 5, title: 'F1 Calendar', icon: 'fa-calendar ',icalurl: 'https://calendar.google.com/.../xx/basic.ics' }
> OR
> calendars.f1 = { maxitems: 5, title: 'F1 Calendar', image: 'img/calendar.png',icalurl: 'https://calendar.google.com/.../xx/basic.ics' }
>

**Comment by robgeerts** [comment]
Fixed in latest beta!
Do not add img/ to the path, just enter: calendar.png
